### ISSUE TITLE
Ils read back

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor#145]
When doing a flight, and if for any reason you need to turn off approach, it will keep reading as if you are still trying to connect. If you want i can do a video and show you if needed.

**Comment by ajborka** [comment]
Attach a video of a landing that gives you this problem. Start it at 10000 feet. Don't forget to describe what you are doing in the video.

**Comment by ajborka** [comment]
This problem seems to be with the PMDG 747. Unlike most PMDG aircraft, the 747 has an approach mode switch and an approach mode light. Typically, the approach light turns on when turning on approach mode. The 747 approach mode light turns on when the ILS is available, and the aircraft is comfortable with locking on to the localizer and glide slope. It is then up to the pilot to turn on approach mode when he/she is ready.
